### ISSUE TITLE
XYZ color spaces now accept percentages too

### ISSUE THREAD

**Issue by svgeesus** [parcel-bundler/parcel-css#106]
https://github.com/parcel-bundler/parcel-css/blob/8ed14cfd6ef1cd0612417b5f8cab5cd6f6a85634/src/values/color.rs#L493

[Fairly recent change](https://drafts.csswg.org/css-color-4/#predefined-xyz), being added to WebKit this week I believe so will be in next Safari TP

**Comment by devongovett** [comment]
Thanks for the heads up!
