### ISSUE TITLE
Bug: Error thrown on `::-webkit-scrollbar-thumb:vertical`

### ISSUE THREAD

**Issue by terebentina** [parcel-bundler/parcel-css#122]
Parcel-css (the version included in parcel 2.4.0) throws when using `::-webkit-scrollbar-thumb:vertical` (or `:horizontal`) although it passes with either `::-webkit-scrollbar-thumb` or `.class::-webkit-scrollbar-thumb` or even the invalid `.class:vertical`.
You can see this in the parcel-css demo app (https://parcel-css.vercel.app) by using the following css:

```
::-webkit-scrollbar-thumb {
}

.a::-webkit-scrollbar-thumb {
}

.a:vertical {
}

::-webkit-scrollbar-thumb:vertical {
}
```
As soon as you remove the last class it compiles.

**Comment by kuangjm825** [comment]
I'm also getting the same error and the CSS I'm compiling has `::-webkit-scrollbar:horizontal`

**Comment by devongovett** [comment]
According to the CSS spec, pseudo elements may only be followed by a user action pseudo class (e.g. `:hover`/`:active`). I guess webkit didn't follow this with their non-standard pseudo elements. 😞 https://www.w3.org/TR/selectors-4/#pseudo-element-states
