### ISSUE TITLE
Local paths with `file://` cause panic

### ISSUE THREAD

**Issue by Jaakkonen** [parcel-bundler/parcel-css#128]
With following files
```css
/* local-file.css */
@import "file://local-file-1.css";
@import "local-file-2.css";
#a {
    display: none;
}

/* local-file-1.css */
#b {
    display: none;
}

/* local-file-2.css */
#c {
    display: none;
}
```
running `parcel-css --bundle local-file.css` causes panic
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" }), loc: Some(ErrorLocation { filename: "local-file.css", line: 0, column: 1 }) }', src/main.rs:76:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  node_modules/.bin/parcel-css --bundle local-file.css
```

The following `local-file.css` works however:
```
/* local-file.css */
@import "local-file-1.css";
@import "local-file-2.css";
#a {
    display: none;
}
```
producing output
```
#b, #c {
  display: none;
}

#a {
  display: none;
}
```
(Which is not optimal even with `--minify` option which produces `#b,#c{display:none}#a{display:none}`)

Thus there seems to be a problem in treating local paths starting with `file://`.
A similar problem also exists in https://github.com/clean-css/clean-css/issues/1210

**Comment by devongovett** [comment]
Where should `file://` urls be resolved relative to? The root of your hard drive? Feels a bit strange. Why not just use a relative path?
