### ISSUE TITLE
Implement `serde::Serialize` on AST

### ISSUE THREAD

**Issue by lucacasonato** [parcel-bundler/parcel-css#143]
This would be very useful for the CSSOM implementation in Deno (also see #5). Many `cssparser` structs already have `serde::Serialize` implementations when you enable the `serde` feature for `cssparser`.

If the binary size increase is too much, we can flag it with a crate feature.

I'll try to open a PR later this week.

**Comment by johno** [comment]
Somewhat relatedly, it'd be great if the properties themselves implement `serde::Serialize`. For my use case I want to run the parser on property values and get that data back via napi in node.

Is this a feature that folks would accept in this project? If not, is there a recommended way to serialize this data without (hopefully) having to implement `Property` and all its variants?

**Comment by devongovett** [comment]
Yep, serde support would be great!

**Comment by devongovett** [comment]
Assuming you didn't start this @lucacasonato. If not I can probably do it this weekend.

**Comment by lucacasonato** [comment]
@devongovett I did start on this actually - I won't be able to push it up until Tuesday unfortunately though (the branch is on a different device).
