### ISSUE TITLE
Valid media query gets stripped from CSS, making it impossible to write styling for devices that support hover

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel-css#152]
# 🐛 bug report

```css
@media not all and (hover: none) {
}
```

Is the counter-intuitive way to write a media query that targets all browsers that support hover, [source](https://stackoverflow.com/a/42363147).
Parcel currently just strips these media queries.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file.

## 🤔 Expected Behavior

```javascript
(()=>{function e(e){return e&&e.__esModule?e.default:e}console.log(e("div{background:green}@media not all and (hover:none){div{background:red}}"))})();
```

## 😯 Current Behavior

```javascript
(()=>{function e(e){return e&&e.__esModule?e.default:e}console.log(e("div{background:green}"))})();
```

## 💁 Possible Solution

Don't strip the rules

## 🔦 Context

Wondered why hover images broke after updating parcel, this is why. Now I'll have to make a JS hack for this 😫

## 💻 Code Sample

Reproduction project: 
[parcel-broken-mediaqueries.zip](https://github.com/parcel-bundler/parcel/files/8458982/parcel-broken-mediaqueries.zip)

styling.scss:

```css
div {
  background: green;
  @media not all and (hover: none) {
    &:hover {
      background: red;
    }
  }
}
```

main.ts:

```javascript
import styling from "bundle-text:./styling.scss";

console.log(styling);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.1041+39b330e74
| Node             |v17.8.0
| npm/Yarn         |3.2.0
| Operating System |macOS 12.2 (21D49)

**Comment by devongovett** [comment]
I think I misinterpreted the spec. It's really `not (all and (hover: none))`, and not `(not all) and (hover: none)`. Strange syntax!
