### ISSUE TITLE
Use Browserslist in `targets` option

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel-css#153]
If we added [`browserslist-rs`] to parse `--targets` argument, can we use it to parse `targets` option in JS API?

The reasons:
1. We can allow missing `targets` and Browserslist well-balanced default will be used. It will be good for browsers diversity.
2. We can simplify main example and avoid byte operations

```diff
-  targets: {
-    // Semver versions are represented using a single 24-bit number, with one component per byte.
-    // e.g. to represent 13.2.0, the following could be used.
-    safari: (13 << 16) | (2 << 8)
-  }
+ targets: 'defaults, not ie 11'
```

If we can’t use string in `targets` because of the types, we can add `browserslist` option for instance.

**Comment by devongovett** [comment]
There is a `browserslistToTargets` util that can convert browserslist results to targets:

```js
let css = require('@parcel/css');
let targets = css.browserslistToTargets(browserslist('>= 0.25%'));
```

We use this in Parcel. I think it's better to do this just once up front, rather than for each file you want to transform, even if it were written in Rust. I suppose we could provide an API to do that with `browserslist-rs` instead of bring-your-own-browserslist, but not sure it's worth it?

**Comment by ai** [comment]
> I suppose we could provide an API to do that with browserslist-rs instead of bring-your-own-browserslist, but not sure it's worth it?

Yes, the idea is that if we already have `browserslist-rs` in the binary, why not use it.

But honestly, it is an open question. If Parcel CSS will be mostly used by bundlers, we do not need high-level API.

**Comment by devongovett** [comment]
At the moment it's only included in the CLI binary, not the Node module binary: https://github.com/parcel-bundler/parcel-css/blob/master/Cargo.toml#L58.

**Comment by ai** [comment]
Got it!

In this case, you can close this issue if you think that JS Browserslist is netter for Node.js binary.

**Comment by devongovett** [comment]
I think you can also use the [browserslist-rs](https://www.npmjs.com/package/browserslist-rs) npm package, which has the same API as `browserslist` so it should already work as in the example above. That's kinda nice I think because it lets users choose.
