### ISSUE TITLE
[Feature Request] Support `generateScopedName` config like `postcss-modules`

### ISSUE THREAD

**Issue by indooorsman** [parcel-bundler/parcel-css#156]
e.g. `generateScopedName: "[name]__[local]___[hash]"`

https://github.com/madyankin/postcss-modules#generating-scoped-names

**Comment by devongovett** [comment]
What's the usecase for this? What are you looking to customize and why?

**Comment by indooorsman** [comment]
@devongovett my usecase is using parcel-css in a legacy frontend project, which has some E2E testing cases using class name as selector of element, e.g.:
```js
cy.get('[class^="some-class-name"]').click()...
```
in the latest version of parcel-css, the class name will be `[hash]_some-class-name`, and it does break my E2E testing cases above.

**Comment by indooorsman** [comment]
btw, I think change position of [hash] is really a breaking change that should be highlighted in release note

**Comment by devongovett** [comment]
Hmm I think the point of css modules is to avoid relying on specific class names, and to keep them locally scoped. The hash position change was necessary to accommodate css grid line names, which the browser may automatically postfix in some cases. I'll have to think about this more.

**Comment by indooorsman** [comment]
> Hmm I think the point of css modules is to avoid relying on specific class names, and to keep them locally scoped. The hash position change was necessary to accommodate css grid line names, which the browser may automatically postfix in some cases. I'll have to think about this more.

how about give developer a chance to choose the hash position?

**Comment by devongovett** [comment]
Well, if it's not at the start then css grid will be broken...

**Comment by indooorsman** [comment]
> Well, if it's not at the start then css grid will be broken...

no css grid in my project 😂
not sure if postcss-modules has css grid issue

**Comment by axyz** [comment]
@devongovett I have an interesting use case for custom `generateScopedName`

https://github.com/utilitycss/atomic is a framework based on postCSS that relies on postcss-modules hevily using composition and relying on a "stable" hashing strategy that guarantees that a hash will only change if the final css rule itself is changed (by default it will change in a number of other cases e.g. adding composes, changing something in the rest of the file, adding a comment, etc...)

I have a long term dream to migrate the project to rust, but doubt it would be feasible a plugin system like in postcss. Said that this project may be a good starting point (not sure if among the goals there is the possibility to include a plugin system).

Just wanted to contribute my use case for a custom `generateScopedName` and also eventually get a hint on where the project is going and if being a substitute for postcss is a long term goal or not.

here you can see the `generateScopedName` function I use, to give an idea: https://github.com/utilitycss/atomic/blob/master/src/postcss/atomic-css-modules/generateScopedName.ts

**Comment by devongovett** [comment]
I think we could provide limited support for this. I wouldn't want to support a callback function where you can do any arbitrary computation in JavaScript because that will slow things down a lot. But we could probably support a pattern syntax like this:

```js
{
  "cssModules": {
    "pattern": "prefix-[name]-[hash]"
  }
}
```

For CSS grid, we'd need to enforce that the hash is added at the start - or rather, that the pattern ends with "[name]".

**Comment by devongovett** [comment]
Working on support for it here if anyone has feedback: #180

**Comment by devongovett** [comment]
I think rather than trying to reproduce the same logic it would be better to just not use `[hash]` at all, and pass it in yourself via the API.

```js
let myHash = computeHash(filename);

parcelCss.transform({
  // ...
  cssModules: {
    pattern: `[local]-${myHash}`
  }
})
```
