### ISSUE TITLE
Issue with pseudoClasses and CSS modules

### ISSUE THREAD

**Issue by lucaseverett** [parcel-bundler/parcel-css#162]
`"pseudoClasses": {
      "focusVisible": "focus-visible"
}`

I'm using the focusVisible pseudoClasses in a project, and I noticed that when using `:focus-visible` using CSS modules, it isn't working. I have to use `:global(:focus-visible)`. Is that intended?

`a:focus-visible {
  color: red;
}`

becomes

`a.AJ453G_focus-visible {
  color: red;
}`

If I use global...

`a:global(:focus-visible) {
  color: red;
}`

becomes

`a.focus-visible {
  color: red;
}`

**Comment by devongovett** [comment]
I think this is working as expected? When CSS modules are enabled, class names are hashed by default.

**Comment by lucaseverett** [comment]
I know this is kind of a strange situation since it's using CSS modules, but if pseudoClasses aren't enabled it works, since it's a standard CSS feature My assumption was that it would work with pseudoClasses  enabled and allow me to write using the standard while using the polyfill.

**Comment by devongovett** [comment]
Hmm, some polyfills let you configure the class name to use... is that an option for you? Otherwise we'd need to make this configurable because sometimes you do want locally scoped classes.

**Comment by lucaseverett** [comment]
After thinking more about it, with current browser support I may not need to continue using the polyfill in my projects. There are also other fallbacks without using the polyfill.
