### ISSUE TITLE
Browser Usage Example

### ISSUE THREAD

**Issue by chriscoyier** [parcel-bundler/parcel-css#173]
The docs have an in-browser usage example:
https://github.com/parcel-bundler/parcel-css#from-deno-or-in-browser

Here's an attempt (only lightly edited not to refer to file):
https://codepen.io/chriscoyier/pen/VwQLWYm

Throws:
> parcel_css_node.js:370 Uncaught Error: invalid type: unit value, expected a string

**Comment by mischnic** [comment]
You need to pass a filename, it's not optional:
https://github.com/parcel-bundler/parcel-css/blob/1b947b480674a170fcac22af0a730b70cfce93a0/node/index.d.ts#L3-L7


```js
let { code, map } = transform({
  filename: "abc",
  code: new TextEncoder().encode(".foo { color: red }")
});
```
