### ISSUE TITLE
Allow for custom URL handling

### ISSUE THREAD

**Issue by jakearchibald** [parcel-bundler/parcel-css#185]
It'd be great if this supported something like https://github.com/postcss/postcss-url#url-function, so the handling of dependencies could be customised.

**Comment by jakearchibald** [comment]
More detail:

I'm looking for a function that's called for ever URL discovered in the source, which returns a value to replace the URL with. This means it can be integrated with other bundling systems.

Bonus points if the function can be async.

The function should be passed the URL, but also details on the source file, so paths can be resolved relative to the file.

**Comment by devongovett** [comment]
Calling into a JS function from Rust will probably slow things down a lot. What are you looking to accomplish? Is a full callback necessary or would some kind of pattern work?

**Comment by jakearchibald** [comment]
With PostCSS I've used this hook to integrate resource discovery into the build system. As in, when a resource is discovered, tell the bundler about it, and replace the URL with either a placeholder or a hashed filename (depending on the build tool).

**Comment by jakearchibald** [comment]
It does! Thanks. I didn't originally discover that from the docs.

For others that might be looking for the same thing, [here's a demo of the output](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Atrue%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40custom-media%20--modern%20(color)%2C%20(hover)%3B%5Cn%5Cnhtml%20%7B%5Cn%20%20background%3A%20url(..%2F..%2Ffoo.webp)%3B%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%201024px)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20background%3A%20url('.%2Fbar.jpg')%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).
