### ISSUE TITLE
Logical shorthand do not work when using variables

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/parcel-css#199]
Hi,

The issue seems to be different from https://github.com/parcel-bundler/parcel-css/issues/171 so I am opening a new issue.

When setting a target of Safari 13, while the following:

```
.foo {
  margin-block: 10px;
}
```

Properly converts to:

```
.foo {
  margin-top: 10px;
  margin-bottom: 10px;
}
```

When using CSS variables the following does not get converted:

```
.foo {
  margin-block: var(--test);
}
```

We would expect it to be:

```
.foo {
  margin-top: var(--test);
  margin-bottom: var(--test);
}
```

I understand the potential issue though: the variable may be a two-value variable, which would cause it to break when expanded. I think if this cannot be solved at the Parcel level, a warning should be emitted in the console such as:

"The property margin-block could not be lowered to match the requirements because it uses variables".

What do you think?

**Comment by devongovett** [comment]
Yep, that's exactly the reason. Shorthand properties with variables are ambiguous. You can either write the physical properties (i.e. margin-top, margin-bottom) yourself if the values are the same, or use the longhand logical properties (margin-block-start/margin-block-end).
