### ISSUE TITLE
detect-libc returns `glibc` on Linux

### ISSUE THREAD

**Issue by cyjake** [parcel-bundler/parcel-css#203]
hence tries to locale package @parcel/css-linux-x64-glibc, 

```bash
[admin@2445c87ab686 /home/admin]
$node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> require('detect-libc').familySync()
'glibc'
>
```

Should `@parcel/css-linux-x64-gnu` be renamed as `@parcel/css-linux-x64-glibc`, or both should be published?

**Comment by cyjake** [comment]
kudos to @killagu

**Comment by cyjake** [comment]
It looks like npm-install does not validate the `${libc}` part, hence both linux-x64-gnu and linux-x64-musl are installed. We use https://github.com/cnpm/cnpm on the other hand, which validates `${libc}` part as well, hence skips both `-gnu` and `-musl`. uhmmm......

**Comment by yisibl** [comment]
@cyjake No need to rename the package name, the error should be introduced by here, not getting the abi correctly.

https://github.com/parcel-bundler/parcel-css/blob/c7545d9c34412bd2dbf3b1977533b6658fd68c4c/scripts/build-npm.js#L36

**Comment by cyjake** [comment]
https://github.com/parcel-bundler/parcel-css/blob/master/scripts/build-npm.js#L7 changing from `-gnu` to `-glibc` seems to be the easiest fix :-/

**Comment by Brooooooklyn** [comment]
@cyjake 

`x86_64-unknown-linux-gnu` is a well-known word combination, it's used in `Rust` `Clang` `GCC` and many other tools. 

There is no `x86_64-unknown-linux-glibc` word.

**Comment by cyjake** [comment]
well, guess the only option left is to alias the abi naming in the build script. AFAICT, both cnpm and yarn support that. I can take a look at it tomorrow.

**Comment by onigoetz** [comment]
Hi, just to be sure, this is related to the change in https://github.com/parcel-bundler/parcel-css/pull/188

that can cause `Cannot find module '../parcel-css.linux-x64-gnu.node` (Node 14 + Yarn 3.2.1 on GitHub Actions) ?

If not I'll open a separate issue.

**Comment by cyjake** [comment]
@onigoetz Yes it's same issue.

**Comment by yisibl** [comment]
A string like `x86_64-unknown-linux-gnu` is called a target in cross-compilation, this format is:

```
<arch><sub>-<vendor>-<sys>-<abi>
```

More details can be resolved via rustc: 
`rustc -Z unstable-options --print target-spec-json --target x86_64-unknown-linux-gnu`

So, instead of renaming, use [`target_env`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_env) disambiguating information about the target platform with information about the `ABI` or `libc` used.

**Comment by cyjake** [comment]
```bash
[admin@14e2f8a21ed0 /home/admin]
$ll node_modules/@parcel/
total 4
lrwxrwxrwx 1 admin admin 34 Jun 17 09:31 css -> ../_@parcel_css@1.10.1@@parcel/css
lrwxrwxrwx 1 admin admin 62 Jun 17 09:31 css-linux-x64-gnu -> ../_@parcel_css-linux-x64-gnu@1.10.1@@parcel/css-linux-x64-gnu
```
verified 💯
