### ISSUE TITLE
[Question]: Any suggestion for good vscode plugin syntax highlight css nesting? thanks

### ISSUE THREAD

**Issue by aelbore** [parcel-bundler/parcel-css#206]
I really wanted to use this but .css files syntax highlight sucks on vscode,  you can close this this issue if not make sense in parcel-css thanks

**Comment by aelbore** [comment]
https://github.com/microsoft/vscode/issues/147824

**Comment by devongovett** [comment]
Not sure. I've always used the "PostCSS language support" extension, and it seems to work fine with nesting.
