### ISSUE TITLE
CSS "@media (min-width: 0\0)" hack causes compilation fail

### ISSUE THREAD

**Issue by julesrx** [parcel-bundler/parcel-css#214]
Hi,

I'm building an app using DevExtreme Dashboard, and in one of their style sheets, the [`@media (min-width: 0\0)` hack](http://browserbu.gs/css-hacks/media-min-width-0-backslash-0/) is used.

However, this cause the compilation to fail.

Minimal repro (`"@parcel/css": "^1.10.1"`) :
```js
const css = require('@parcel/css');

// Source file : https://unpkg.com/@devexpress/analytics-core@21.2.8/dist/css/dx-analytics.common.css
const { code } = css.transform({
  filename: 'style.css',
  code: Buffer.from(`
      @media screen and (min-width:0\0) {
          .dxd-track-cursor {
              background-color: rgba(255, 255, 255, 0);
          }
      }
  `),
});

console.log(code.toString());
```

[Playground link](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%7D%2C%22source%22%3A%22%40media%20screen%20and%20(min-width%3A0%5C%5C0)%20%7B%5Cn%20%20%20%20.dxd-track-cursor%20%7B%5Cn%20%20%20%20%20%20%20%20background-color%3A%20rgba(255%2C%20255%2C%20255%2C%200)%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

This issue has also been submitted to the DevExpress support, but I doubt a fix could be easily deployed at their end, since this is specific IE code.
Is there any work-around ?

**Comment by devongovett** [comment]
Sorry, but IE hacks are not supported. IE is officially unsupported by Microsoft.

One way to work around is to patch the dependency yourself with something like patch-package. Or fork and submit a fix if you can.

**Comment by daviddeutsch** [comment]
Note: You can also use the `--error-recovery` flag to have this still compile.
