### ISSUE TITLE
Fallbacks and RTL not generated if margin-inline value is a CSS variable

### ISSUE THREAD

**Issue by jamcow** [parcel-bundler/parcel-css#217]
Correct RTL fallbacks are generated for `*-start` and `*-end` properties that have a CSS variable for the value (eg `margin-inline-start: var(--v)`. But not if the property is inline (eg, `margin-inline: var(--v)`). And if it's `margin-block: var(--v)` the fallback is not generated.

[Playground example comparing output of CSSvars and px values](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22ios_saf%22%3A524288%7D%2C%22source%22%3A%22.test1%20%7B%5Cn%20%20padding-inline-start%3A%20var(--size-1)%3B%5Cn%20%20margin-inline%3A%20var(--size-2)%20var(--size-3)%3B%5Cn%20%20inset-inline%3A%20var(--size-4)%3B%5Cn%7D%5Cn%5Cn.test2%20%7B%5Cn%20%20padding-inline-start%3A%2010px%3B%5Cn%20%20margin-inline%3A%2020px%2030px%3B%5Cn%20%20inset-inline%3A%2040px%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D). Pixel values in fallbacks are correctly generated (left/right depending on language, block to top/bottom). I would expect the CSSvars to match the fallback output.

```
.test1 {
  padding-inline-start: var(--size-1);
  margin-inline: var(--size-2) var(--size-3);
  inset-inline: var(--size-4);
}
```
generates
```
.test1 {
  margin-inline: var(--size-2) var(--size-3);
  inset-inline: var(--size-4);
}

.test1:not(:lang(ae)):not(:lang(ar)):not(:lang(arc)):not(:lang(bcc)):not(:lang(bqi)):not(:lang(ckb)):not(:lang(dv)):not(:lang(fa)):not(:lang(glk)):not(:lang(he)):not(:lang(ku)):not(:lang(mzn)):not(:lang(nqo)):not(:lang(pnb)):not(:lang(ps)):not(:lang(sd)):not(:lang(ug)):not(:lang(ur)):not(:lang(yi)) {
  padding-left: var(--size-1);
}

.test1:-webkit-any(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  padding-right: var(--size-1);
}

.test1:is(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  padding-right: var(--size-1);
}
```

**Comment by bakura10** [comment]
This is expected. You can find the reason there: https://github.com/parcel-bundler/parcel-css/issues/199

**Comment by jamcow** [comment]
Thank you - and yes, that makes sense with CSS variables output.
I guess I was also expecting/used to simplistic text replacement of the property via PostCSS plugins from previous non-Parcel builds.
