### ISSUE TITLE
WASM package includes a broken "exports" field

### ISSUE THREAD

**Issue by binyamin** [parcel-bundler/parcel-css#222]
Probably introduced in commit https://github.com/parcel-bundler/parcel-css/commit/d004c2fd3d04e2386fc4151320b457f54b023f19.

There's a broken `exports` field in the WASM package's `package.json`. It points to a non-existent file. Because of this, esm.sh isn't able to parse the package.

https://github.com/parcel-bundler/parcel-css/blob/a1f4401e829b7ab616a2df305372eca3e5fcb146/package.json#L8-L11

**Comment by mischnic** [comment]
And for the other platform-specific packages, it also refers to a missing file: https://unpkg.com/browse/@parcel/css-win32-x64-msvc@1.11.0/
