### ISSUE TITLE
`:where()` with pseudo elements doesn't seem to be compiling correctly. 

### ISSUE THREAD

**Issue by nicksrandall** [parcel-bundler/parcel-css#226]
Repo: https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%3Awhere(.root%20*%2C%20.root%20*%3A%3Abefore%2C%20.root%20*%3A%3Aafter)%20%7B%5Cn%20%20box-sizing%3A%20border-box%3B%5Cn%7D%5Cn%5Cn*%2C%20*%3A%3Abefore%2C%20*%3A%3Aafter%20%7B%5Cn%20%20box-sizing%3A%20border-box%3B%5Cn%7D%5Cn%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by devongovett** [comment]
Pseudo elements are not valid within `:is` or `:where`. See spec: https://www.w3.org/TR/selectors-4/#matches

> Pseudo-elements cannot be represented by the matches-any pseudo-class; they are not valid within [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo).
