### ISSUE TITLE
property is support non-alphanumeirc character such as an asterisk(*)?

### ISSUE THREAD

**Issue by IDKNWHORU** [parcel-bundler/parcel-css#233]
looks like occured syntax error, when style property includes asterisk.
how to possible non-alphanumeric character?

![image](https://user-images.githubusercontent.com/49608580/179445064-727d55bc-728d-4826-a0aa-c8573a36920d.png)

**Comment by devongovett** [comment]
That's invalid. Probably some kind of IE hack. If you can edit the css, you should remove it. Otherwise, try the errorRecovery option to skip over it.
