### ISSUE TITLE
any plan to support purge ?

### ISSUE THREAD

**Issue by lili21** [parcel-bundler/parcel-css#235]
just like purge css

**Comment by tanishqkancharla** [comment]
That’s not really within the scope of this lib. Purge css is a build step that analyzes code statically to figure out what css you are and aren’t using. @parcel/css is specifically for minifying and transforming css itself, and performing static analyses on the usage of the css is something completely different.

**Comment by devongovett** [comment]
Not sure if still being worked on but @deckchairlabs was working on something like this here https://github.com/deckchairlabs/purginator
