### ISSUE TITLE
Download CLI?

### ISSUE THREAD

**Issue by joelmoss** [parcel-bundler/parcel-css#241]
It would be amazing if we could download any given release of the CLI. It looks like the GH actions do build for each target, but not seeing where they are uploaded to, other than as an NPM package.

I simply need the Rust compiled binary for each target. Are they available somewhere? If not, could we perhaps make them available alongside the source assets in each GH release?

thx loads!

**Comment by devongovett** [comment]
You could download the tarball from the npm registry

**Comment by joelmoss** [comment]
Yeah that's what I just started doing actually. That'll do, thx.
