### ISSUE TITLE
Ignore lines from the compilation step?

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/parcel-css#244]
Hi :),

Our use case is a bit special, but we are working on Shopify, where we can generate .css.liquid file. We would like to be able to use Liquid condition to easily implement some custom logic based on settings. For instance:

```
{% if settings.enable_button_animation %}
  .button:hover {
    // Do the animation
  }
{% endif %}
```

The lack of conditions with CSS variable make it necessary for us. However, this won't compile (of course).

I don't know if such approach would map to ParcelCSS architecture, but by doing annotation to basically indicate parcel to not interpret a line and output it "as it" (would compile as the previous code) :

```
/* __OUTPUT__ {% if settings.enable_button_animation %} */
  .button:hover {
  }
/* __OUTPUT__ {% endif %} */
```

Thanks :)

**Comment by bakura10** [comment]
Actually I just realized we do not need that. We just need an option for ParcelCSS to preserve the comments. If ParcelCSS can preserve comment, then we could simply write this valid CSS:

```
/* {% if settings.enable_button_animation %} */
  .button:hover {
    // Do the animation
  }
/* {% endif %} */
```

Once processed by Liquid engine, if the setting is false, it would compile to:

```
/* */
```

Which does exactly what we need. Allow to preserve comments has been asked here (https://github.com/parcel-bundler/parcel-css/issues/43), but here is an extra use case where it would be very useful!

**Comment by devongovett** [comment]
Dup of #43. This will be very hard, so won't happen any time soon.
