### ISSUE TITLE
how to concat multiple css files into one file ?

### ISSUE THREAD

**Issue by lili21** [parcel-bundler/parcel-css#248]

**Comment by lili21** [comment]
or maybe transform @import rules by inlining content?

**Comment by mischnic** [comment]
> or maybe transform @ import rules by inlining content?

That is already possible and called "bundling" in the readme: https://github.com/parcel-bundler/parcel-css#:~:text=Bundling%20is%20also%20possible%20by%20using%20the%20bundle%20API.%20This%20processes%20%40import%20rules%20and%20inlines%20them.%20This%20API%20requires%20filesystem%20access%2C%20so%20it%20does%20not%20accept%20code%20directly%20via%20the%20API.

**Comment by lili21** [comment]
@mischnic does it support to import node_modules styles? 

```css
@import 'third-party/style/index.css'
```

**Comment by mischnic** [comment]
I don't think so
