### ISSUE TITLE
File selector button workaround

### ISSUE THREAD

**Issue by lukewarlow** [parcel-bundler/parcel-css#26]
The latest version of [autoprefixer](https://github.com/postcss/autoprefixer/releases/tag/10.4.1) should remove the need for the workaround for file selector button data.

**Comment by devongovett** [comment]
Thanks! I tried to update, but a few tests seem to fail.

* `tab-size` - for some reason, Android Firefox 94 is marked as needing prefixes: https://caniuse.com/css3-tabsize. Looks like it happened in https://github.com/Fyrd/caniuse/commit/3440e6f9751fef46267bcbdf223fa7fe5845c9ee#diff-625786136c02808151987347b07b2cd2b4a83f32b841a0a52c5b60c1a2cb8c16
* `:fullscreen` - Android Chrome 96 is marked as needing prefixes.

I think both of these are wrong. MDN shows them as supported. Perhaps bugs in the data?

**Comment by devongovett** [comment]
Filed https://github.com/Fyrd/caniuse/issues/6132
