### ISSUE TITLE
Use more stable hash for CSS modules

### ISSUE THREAD

**Issue by ArnaudBarre** [parcel-bundler/parcel-css#265]
I just noticed that the hash for the CSS modules is based on the file path. This is great to avoid clashes on a given project, but it breaks build reproducibility between environment (CI or between devs).

This breaks some tests for me for a build tool that is using @parcel/css. This could also be more problematic for tools like turborepo. 

Maybe we could use a relative path (from working directory, output path, git root, not sure which one will be a better fit) or a hash of the content (hopping that 62**5 is enough to avoid collision)

**Comment by devongovett** [comment]
How are you using Parcel CSS? If you are using Parcel, we already pass in a relative path. https://github.com/parcel-bundler/parcel/blob/3329469f50de9326c5b02ef0ab1c0ce41393279c/packages/transformers/css/src/CSSTransformer.js#L74

**Comment by ArnaudBarre** [comment]
Oh yeah my bad I was passing the full path to the transform function (directly using the node package). Passing a relative path there is way better for error messages and source map too.

Sorry for the inconvenience and thanks for the quick reply!
