### ISSUE TITLE
Improve installation size

### ISSUE THREAD

**Issue by yyx990803** [parcel-bundler/parcel-css#38]
Currently `@parcel/css` includes `.node` files for all platforms regardless of target platform, which results in ~32mb disk space usage.

Is there any reason for not selectively installing the platform-specific binary (via optional dependencies) like esbuild does? That could bring down the download size significantly to ~4mb (although results in more resolution http calls).

**Comment by devongovett** [comment]
Ugh, I really wish npm had a better way of solving this. I don't particularly like the registry clutter introduced by architecture specific packages, but I suppose we could do it if disk space is really a concern for people.

**Comment by yyx990803** [comment]
We are interested in using `@parcel/css` in Vite, but it's hard to justify a 32mb increase when Vite itself (esbuild included) is just ~20mb.

**Comment by devongovett** [comment]
Done in v1.0.1.
