### ISSUE TITLE
unusedSymbols doesn't work with selectors like `.foo` or `#bar`

### ISSUE THREAD

**Issue by deckchairlabs** [parcel-bundler/parcel-css#40]
Unsure if this is how unusedSymbols is intended to work.

But say I have the following:

```js
const { code } = css.transform({
    filename: 'style.css',
    code: Buffer.from(`
        .foo .bar {
            color: red;
        }

        .bar {
            color: green;
        }

        #foo {
            color: blue;
        }
    `),
    minify: true,
    unusedSymbols: ['#foo'],
})
```

The resulting code is:

```css
.foo .bar{color:red}.bar{color:green}#foo{color:#00f}
```

Whereas

```js
const { code } = css.transform({
    filename: 'style.css',
    code: Buffer.from(`
        .foo .bar {
            color: red;
        }

        .bar {
            color: green;
        }

        #foo {
            color: blue;
        }
    `),
    minify: true,
    unusedSymbols: ['foo'],
})
```

Produces:

```css
.bar{color:green}
```

I would expect to be able to pass selectors to `unusedSymbols` as the typedocs mention as such https://github.com/parcel-bundler/parcel-css/blob/40868cbb111a13551a508629aa0d11c5e9204c64/node/index.d.ts#L30-L35

**Comment by devongovett** [comment]
The second example is correct. You specify individual names that are unused, not full selectors. It's mainly intended for use with CSS modules, which treats id and class names the same way. Parcel implements tree shaking of CSS modules this way.

Can improve the docs on this.

**Comment by deckchairlabs** [comment]
I see, not a problem!
