### ISSUE TITLE
Additional CLI features

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel-css#52]
As of #44 we have a basic CLI. Currently it can minify and output to stdout or a file, but might be nice to add a few more features.

* `--targets` option. Could accept a browserslist and convert them to Parcel CSS targets with `browserslist-rs` (see #37).
* `--sourcemap` option. Should output a source map file in addition to a css file, and add a `sourceMappingUrl` comment to the CSS.
* `--nesting` option to enable parsing CSS nesting.
* `--css-modules` option to enable CSS modules. Output a JSON file in addition to compiled CSS?
* Ability to compile multiple files at once, either by passing file names or directories.

**Comment by Shinyaigeek** [comment]
I think it is a good idea to add CLI flags to specify `parcel-css`’s feature.

I think it would be also good to add loading a config file `.parcelcssrc` like `.swcrc` to specify `parcel-css`’s feature as well as CLI flag, because in real development, devs may want to specify which ‘parcel-css`’s feature is ON with a static config file. What do you think about this idea?

**Comment by devongovett** [comment]
Maybe, but I feel like at that point you should probably be using another build tool like a bundler. For example, like Parcel [supports](https://github.com/parcel-bundler/parcel-css#with-parcel). I was thinking that the Parcel CSS CLI would mainly be used for very simple use cases, as well as debugging/testing. Will have to think about it more, but I don't want to jump straight to config files if we can help it. 😄

**Comment by Shinyaigeek** [comment]
Well, in fact,  few devs touch `.swcrc` directory and many devs handle swc feature via bundler. It would be better to implement only CLI flag and collect feedback from developers, and if there are many requests for such a config file, we would rethink 😄 .

**Comment by devongovett** [comment]
Maybe we could also use miette to get pretty error messages: https://github.com/zkat/miette

**Comment by devongovett** [comment]
Also need to figure out a nice way of distributing the CLI. Right now you can install with `cargo` but that means you need to compile it yourself. We could potentially publish binaries to npm, or via direct download or something...

**Comment by numToStr** [comment]
Hey, I was wondering are you planning to add subcommands? Or just bunch of flags and options to control the behaviour.

**Comment by devongovett** [comment]
We could add some, but not sure what they would be. Did you have one in mind? Right now there's `parcel_css minify` but maybe it should be `--minify` so you could choose whether to enable it or not.

**Comment by joelmoss** [comment]
I don't think subcommands are the right fit here, as you want to be able to mix the options, just like you can with the API. They should be flags.

**Comment by numToStr** [comment]
Yeah, I also think that flags and options will be the best choice here.

**Comment by joelmoss** [comment]
And ideally they should match the API options

**Comment by rrcobb** [comment]
I've got a[ branch where I've started adding some of these](https://github.com/rrcobb/parcel-css/tree/cli-features).

Leaving it for the night. I've started to write cli integration tests, and will hopefully wrap tomorrow with a good chunk of them done. 

for sourcemap and css module files, I think it's probably right to make decent guesses about what the additional output files should be named, but only write to files if the output file option is specified. If not, putting them on stdout seems right, I think.

Questions:
- multiple files option - do we just concat the files to pass them to `Stylesheet::parse`? If so, what should the 'filename' arg be?
- for the 'directory' option for multiple files, how should the tree walking pick valid files?
- how should sourcemap and css module json get formatted on stdout, when no output file is specified? (e.g. add a comment like `/* styles.json */` to the output to distinguish them?)

**Comment by shrirambalaji** [comment]
Can multiple folks contribute towards this?

**Comment by rrcobb** [comment]
> Can multiple folks contribute towards this?

Probably yes - my branch certainly isn't intended to cut off other contributions, I'm not affiliated with the project, just a web stranger.

It doesn't look like there's a contributors guide specific to this repo, so I'm inferring from parcel js's [CONTRIBUTING.md](https://github.com/parcel-bundler/parcel/blob/v2/CONTRIBUTING.md) and typical open source contribution ethos, but it's pretty normal for different folks to work on the same feature in parallel. At worst, there's some duplicated effort or bad feelings depending on the eventual outcome, but that's probably okay!

**Comment by devongovett** [comment]
Added `--targets` in 7d9cec033f17c7b4cf8c0455abf9341d55adc5ad.
