### ISSUE TITLE
Parse StyleSheet &str in-memory

### ISSUE THREAD

**Issue by cryptoquick** [parcel-bundler/parcel-css#59]
I'd like to minify my stylesheet in-memory, since in my app, it's generated from CSS-in-RS using stylist and then the app is pre-rendered in SSR, so the CSS is never kept on-disk.

Maybe if a trait was used that parsed either a Path on-disk or &str (for CSS in-memory) for this function:
https://docs.rs/parcel_css/1.0.0-alpha.11/parcel_css/stylesheet/struct.StyleSheet.html#method.parse

**Comment by devongovett** [comment]
The `parse` function doesn't read anything from disk. The `filename` parameter is only used for source maps and error messages, and the code is passed in as a string. If you don't know where the CSS is coming from, you could make something up. Did I understand your question right?

**Comment by cryptoquick** [comment]
Oh! Makes sense. I guess I didn't read the entire function signature. Is the filename parameter for output or input? If it's for input, what happens if I give it an empty string? If it's for output, could I just point it to "/dev/null" ?

**Comment by devongovett** [comment]
It's the file where the input CSS source code came from. An empty string or something hard coded like "source.css" should work if you don't know where it came from.

**Comment by cryptoquick** [comment]
Makes sense! I'll try it out, thanks!
