### ISSUE TITLE
How to get CssRule as a selector string?

### ISSUE THREAD

**Issue by deckchairlabs** [parcel-bundler/parcel-css#61]
I'm starting to get my head around Rust, slightly. As a good little challenge and starter project I'm attempting to recreate https://github.com/FullHuman/purgecss using this library, find progress here https://github.com/deckchairlabs/purginator.

Is there an better way to get the Selector components into a string? I'm not sure how to do it correctly for the NestedRule

I'm currently doing the below:

https://github.com/deckchairlabs/purginator/blob/83a246d658e74bd02b5309ee6804d4f5ecdd6ed5/purginator/src/purger.rs#L8-L17

**Comment by devongovett** [comment]
You've got the right idea. Two ways to simplify:

1. `SelectorList` also implements the `ToCss` trait, so you can serialize the whole thing at once rather than each individual selector.
2. The `ToCss` trait also has a `to_css_string` method.

So this should do it:

```rust
style_rule.selectors.to_css_string()
```

**Comment by deckchairlabs** [comment]
Ah! So simple, now to just fix the logic!
