### ISSUE TITLE
Mozilla Public License 2.0 compliance issue

### ISSUE THREAD

**Issue by mhoye** [parcel-bundler/parcel-css#62]
Hi, Parcel-CSS team. My name is Mike Hoye, and I work for Mozilla.

We've noticed that you've re-used a substantial amount of the Firefox style system code in parcel-css; for example, compare

* https://github.com/parcel-bundler/parcel-css/blob/9f93ab05672b06c9b71ab4a3edf1c4d1380f6953/src/media_query.rs#L192-L240
 
and 

* https://searchfox.org/mozilla-central/rev/5ce782034b736293836a2850ab698e149ca04657/servo/components/style/media_queries/media_condition.rs#96-144

While that's OK and we're always happy to see Mozilla code finding new life in new projects, we license it under the Mozilla Public License, rather than the MIT license parcel-css is using, and modified MPL-licensed code should remain covered by the MPL. I'm sure this was an unintentional oversight, but we'd appreciate it if you could make the necessary corrections in those files relying on Mozilla-created code.. 

Thank you, and you can reach me at mhoye at mozilla dot com if you have any questions.

- mhoye

**Comment by devongovett** [comment]
No problem. What would the best way to resolve this? A notice file or section in the LICENSE file at the root of the repo that states that portions of the code are licensed under the MPL would be easiest since it covers all files that may have modified Mozilla code. Is that acceptable?

**Comment by devongovett** [comment]
Added NOTICE in 49cbb536b71e17113c5726a1797a98c41a9f0016.

**Comment by devongovett** [comment]
Going to close this. If there are any further changes you'd like to see, please let me know!

**Comment by mhoye** [comment]
I think you're close to where you need to be, but the MPL is a per-file license, not per-line or code block, so if you'd prefer not to relicense the whole project under the MPL (which is totally fine), at least the MPL-derived code will need to be in specified files that are shared under the MPL.

**Comment by devongovett** [comment]
@mhoye thanks, yeah, I realized this when #64 was opened and I did some further research. Splitting the code up that way was too difficult, so I simply relicensed the project under the MPL in https://github.com/parcel-bundler/parcel-css/commit/3e8f71ef3729879872e78f4cb2cc6f22cd2597ad.
