### ISSUE TITLE
Nesting transform is incorrect?

### ISSUE THREAD

**Issue by evanw** [parcel-bundler/parcel-css#67]
First, thank you for making this library. It's wonderful to see something like this, especially as an independent library, and I know how much work it is to make one of these.

I looked into transforming CSS nesting in esbuild recently and I was wondering how this library does it. I think I've found a case where this implementation deviates from [the CSS nesting specification](https://drafts.csswg.org/css-nesting/):

```css
.foo .bar {
  &div { color: red }
}
```

This library transforms that into this code ([live link](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20.bar%20%7B%5Cn%20%20%26div%20%7B%20color%3A%20red%20%7D%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%7D)):

```css
div.foo .bar{color:red}
```

However, if I'm reading it correctly the specification says this should be transformed into the following code instead ([in this section](https://drafts.csswg.org/css-nesting/#nest-selector)):

```css
div:is(.foo .bar){color:red}
```

These two code snippets are not equivalent. For example, the following HTML is supposed to render as black if the specification is followed, but renders as red with the output from this library:

```html
<div class="foo">
  <span class="bar">stuff</span>
</div>
```

Just letting you know about this edge case. I don't need this edge case to work since I'm not using your library myself. Feel free to do what you want with this issue.

Potentially related: #19

**Comment by devongovett** [comment]
Yeah you are correct. Another way to do it would be `.foo .bar:is(div)` or `.foo div.bar`. There's some complicated logic to deal with type selectors, which must always come first in a selector, so probably a bug in that somewhere. I'll look into it soon. Thanks for the report!
