### ISSUE TITLE
Missing dependency detect-libc

### ISSUE THREAD

**Issue by onigoetz** [parcel-bundler/parcel-css#7]
I was trying to add `@parcel/css` to https://github.com/GoalSmashers/css-minification-benchmark

running this package complains about a missing `detect-libc` package.

(On a side note, I added the package manually and @parcel/css is indeed the fastest in all cases, it does seem to trigger a `ParseError { kind: Basic(EndOfInput), location: SourceLocation { line: 18, column: 79 } }` on `gumby.css` though)

Looking forward for the future of this library, it's very promising !

**Comment by mischnic** [comment]
Reproduction for that parser error:
```css
/* xyz */
@import url(a.css);
```

**Comment by devongovett** [comment]
Ah, it's not actually an error, just a debug statement I forgot to remove. Removed in 87d82873f72f1b84bb87c8a57a8e70b28b243843. The media query parser is still WIP. 😂 

Thanks for testing it out btw!

**Comment by devongovett** [comment]
Released a new alpha that should fix these issues.

**Comment by onigoetz** [comment]
Awesome, I was able to PR the benchmark :) https://github.com/GoalSmashers/css-minification-benchmark/pull/101

I'll test it in my workflows and with the stylesheets we have at work, I am curious to see the results.
I'll report any problem I find :)
