### ISSUE TITLE
`list-item: none` broken with CSS-Modules turned on.

### ISSUE THREAD

**Issue by nicksrandall** [parcel-bundler/parcel-css#73]
SEE: https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.list%20%7B%5Cn%20%20list-style%3A%20none%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D

**Comment by devongovett** [comment]
Ah, good catch! Looks like the order of these conditions should be switched:

https://github.com/parcel-bundler/parcel-css/blob/0d2844eed6cc9c82aa3e6983205146c242b67289/src/properties/list.rs#L27-L33
