### ISSUE TITLE
Output has 8-char hex if Target list includes one newer browser that supports it

### ISSUE THREAD

**Issue by jamcow** [parcel-bundler/parcel-css#77]
I have a Parcel build (using default CSS setup) with multiple targets (modern/legacy) which all worked as expected, but after swapping the CSS setup for this one (+ testing standalone, + playground) is producing newer 8-charcter HEX colour if one of the browsers does support it, even if the others don't.

```css
.foo {
color: rgba(255, 105, 180, 0.219); /* rgba */
border-color: #ff69b438; /* 8 character hex */
outline-color: rgba(123 56 17 / 0.45) /* space separated */
}
```

[Playground example](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22firefox%22%3A3145728%2C%22safari%22%3A589824%2C%22ios_saf%22%3A589824%7D%2C%22source%22%3A%22.foo%20%7B%5Cncolor%3A%20rgba(255%2C%20105%2C%20180%2C%200.219)%3B%5Cnborder-color%3A%20%23ff69b438%3B%5Cnoutline-color%3A%20rgba(123%2056%2017%20%2F%200.45)%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D) Given two or more browsers in the Targets list (Safari & iOS v10 supports 8 character hex, v9 doesn't) - but the output is 8 character hex if any one browser is newer. I'd expect it to choose the lower browser to decide the output, because it's in the Target list.

Both browsers to v9 = `rgba`
One Safari browser to v10, one to v9 = `8-hex`, but I expected `rgba` because there's still an older browser in the list.

Not just Safari's but Firefox 48/49, Chrome 61/62 produces same output (8 char hex if one supports it is in the Targets list).
Perhaps it's just colour? A pre-fixed property works as expected eg, `display:flex` shows a prefix for iOS v8. [flex example](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22firefox%22%3A3211264%2C%22safari%22%3A589824%2C%22ios_saf%22%3A524288%7D%2C%22source%22%3A%22.foo%20%7B%5Cncolor%3A%20rgba(255%2C%20105%2C%20180%2C%200.219)%3B%5Cnborder-color%3A%20%23ff69b438%3B%5Cndisplay%3Aflex%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)

This is using `build` and `targets`, so doesn't seem to be [#56 ](https://github.com/parcel-bundler/parcel-css/issues/56) but similar to [#65 ](https://github.com/parcel-bundler/parcel-css/issues/65) if you target both Safari v15 and iOS v14 [at the same time](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A983040%2C%22ios_saf%22%3A917504%7D%2C%22source%22%3A%22.foo%20%7B%5Cnposition%3A%20absolute%3B%5Cntop%3A%200%3B%5Cnright%3A%200%3B%5Cnbottom%3A%200%3B%5Cnleft%3A%200%3B%5Cndisplay%3A%20flex%3B%5Cnflex-direction%3A%20column%3B%5Cnalign-items%3A%20flex-start%3B%5Cnjustify-content%3A%20center%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D).

**Comment by devongovett** [comment]
Thanks, this was a great catch! The logic was certainly incorrect here.
