### ISSUE TITLE
error[E0515]: cannot return value referencing temporary value

### ISSUE THREAD

**Issue by joshstoik1** [parcel-bundler/parcel-css#83]
Hi there!

I'm getting the following error when adding the latest release (`1.0.0-alpha.15`) as a project dependency, but _not_ when running `cargo check` directly against the contents of the `parcel-css` repo (the latter works just fine):

```
# cargo check
    Checking parcel_css v1.0.0-alpha.15
error[E0515]: cannot return value referencing temporary value
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/parcel_css-1.0.0-alpha.15/src/bundler.rs:49:5
   |
45 |       let res = self.inputs.entry(file.to_owned())
   |  _______________-
46 | |       .or_insert(source)
47 | |       .downgrade()
   | |__________________- temporary value created here
48 |         .value();
49 |       Ok(res)
   |       ^^^^^^^ returns a value referencing data owned by the current function
```

It doesn't seem to matter whether or not the project actually _uses_ parcel; simply adding the dependency line is all it takes for me to get the error. The following `cargo init` boilerplate, for example, triggers it:
```toml
[package]
name = "just_a_boilerplate"
version = "0.1.0"
edition = "2021"

[dependencies.parcel_css]
version = "1.0.0-alpha.15"
```

I tried linking directly to git/master, toggling the "cli" feature on and off, and tested both stable `1.58.1` and nightly compilers, but none of that made any difference.

My build machine is a Debian Bullseye Docker environment (x86_64-unknown-linux-gnu).

I didn't have any issues with prior releases, but since the error is in `bundler.rs`, I suppose that doesn't mean much. Haha.

**Comment by devongovett** [comment]
I haven't tested yet (on mobile), but looks like perhaps the new version of dashmap might have changed some lifetimes: https://github.com/xacrimon/dashmap/issues/167. It's set to 5.0.0 in the Cargo.lock in the repo so might be why it works there. I'll take a look in the morning.

**Comment by joshstoik1** [comment]
Ah yep, that's it exactly. Running `cargo update` against master and then `cargo check` is enough to bring about the error. :wink:

**Comment by ije** [comment]
<img width="931" alt="Screen Shot 2022-02-15 at 14 54 40" src="https://user-images.githubusercontent.com/2883484/154008663-0eb1fd52-bac4-44be-b6f9-8d571e55b77b.png">

i also got the same error after upgraded to `1.0.0-alpha.15`.

**Comment by ije** [comment]
@devongovett thanks

**Comment by devongovett** [comment]
So I implemented a different approach, but ended up relying on some unsafe rust unfortunately. If anyone knows a better way to accomplish this, let me know.

It's late here, so I'll get this released in the morning.

**Comment by ije** [comment]
@devongovett thanks no worries, good night

**Comment by ije** [comment]
i am not expert of rust, fyi https://github.com/denoland/deno_graph/blob/main/src/source.rs seems has the same file handling op

**Comment by joshstoik1** [comment]
Yeah, there isn't really a safe way to return to non-Copy content that lives behind a Mutex. You could try replacing String with something like [ustr](https://crates.io/crates/ustr), but they use pointer magic too.
